### ISSUE TITLE
Peer Review su

### ISSUE THREAD

**Issue by amanjain454** [muralits98/Predicting-Wild-Fire-with-Weather-Data-in-the-US-Geography#1]
The team is working to predicting the weather conditions in the US and predict wildfires well in advance based on this data. They are using kaggle datasets of wildlife fire history and hourly weather data with the objective of saving wildlife by predicting these fires well in advance. 

Things I liked about the proposal: 
1. Focussed on "burning" need of the time (pun intended !). 
2. Dataset is rich in volume and attributes. It would be interesting to play around with. 
3. The topic provided opportunity to apply models learned in the course. 

Possible improvement area: 
1. Problem statements could be made more specific in order to be effective. I am not sure if the same model can be applied to all parts of US or all fire types (say human triggered). 
2. The proposal talks about three different predictions - predicting future weather conditions, predicting fire possibilities and predicting fire intensities - which might be too much, my suggestion would be to focus on 1 or 2 of these and go deeper in those. 
3. In order to make proposal more strong and impact, you can also evaluate it from point of view of greenhouse gases being added to the environment by these fires.

**Comment by muralits98** [comment]
Wow. Thank you for your suggestions! @amanjain454
