### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by Ddottsai** [muralits98/Predicting-Wild-Fire-with-Weather-Data-in-the-US-Geography#2]
I love the approach you've taken to combine these two datasets. Considering the environmental, monetary, and social impact of large wildfires, and in light of recent massive wildfires throughout the world, this research is of particular importance.

I'd say my biggest concern is a mismatch in the types of information in the two datasets. While the weather dataset only has information on very large cities, the fires dataset likely does not have much information on large cities (since wildfires tend not to happen close to very large cities). If your two datasets end up not mixing well, you could consider combine your weather predictor with other people's weather predictors (giving them credit, of course).

A side note: if the data you have proves to not be enough to effectively predict wildfires, I would suggest that you try to find information on soil aridity or vegetation levels.

Overall, I'm really excited to see what comes of this project -- the results could have drastic implications for wildfire prevention, safety, and suppression.

**Comment by muralits98** [comment]
Thank you for your suggestions @Ddottsai !

The match happens only in the major cities. For the other cities, we'd love to use the idea of using someone's model and compare it.
